---
title: "Bird Joins"
author: "Desik Somasundaram"
date: "8/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

## Task 1: Joins on birds

### Read in data

```{r}
bird_observations <- read_csv(here("data", "52_pp52_birds_1.csv"))
sites <- read_csv(here("data", "52_pp52_sites_1.csv"))
surveys <- read_csv(here("data", "52_pp52_surveys_1.csv"))
taxalist <- read_csv(here("data", "52_pp52_taxalist_1.csv"))
```
### Subset

```{r}
birds_subset <- bird_observations %>% 
  filter(species_id %in% c("BHCO", "RWBL")) %>% 
  filter(site_id %in% c("LI-W", "NU-C"))
```

### Left join

```{r}
birds_left <- left_join(x = birds_subset, y = sites, by = "site_id") 
birds_left2 <- left_join(x = birds_left, y = taxalist, by = "species_id") 
```

### Full join

```{r}
birds_full <- full_join(x = birds_subset, y = sites, by = "site_id")
```

### Inner join

```{r}
birds_inner <- inner_join(x = birds_subset, y = taxalist, by = "species_id")
birds_left_test <- left_join(x = birds_subset, y = taxalist, by = "species_id")
```

## Task 2: Dat wrangling and visualization with birds

```{r}
birds <- bird_observations %>% 
  rename(bird_obs_notes = notes)

birds_allsubset <- left_join(x = birds, y = taxalist, by = "species_id") %>% 
  left_join(y = sites, by = "site_id") %>% 
  left_join(y = surveys, by = "survey_id") %>% 
  select(survey_date, common_name, park_name, bird_count) %>% 
  mutate(survey_month = lubridate::month(survey_date)) %>%
  mutate(survey_month = as.factor(survey_month)) %>% 
  relocate(survey_month, .after = survey_date)
  
bird_summary <- birds_allsubset %>% 
  group_by(park_name, survey_month) %>% 
  summarize(n= n()) %>% 
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa"))



```

